import Head from 'next/head';
import styles from '@/styles/Home.module.css';
export default function Home({ categories, products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {products.map((product) => (
          <div key={product._id}>
            <h1>{product.title}</h1>
          </div>
        ))}
        {categories.map((category) => (
          <div key={category._id}>
            <h1>{category.title}</h1>
          </div>
        ))}
      </main>
    </>
  );
}

Home.getInitialProps = async (ctx) => {
  const productsResponse = await fetch(`${process.env.DB_HOST}/api/products`);
  const categoriesResponse = await fetch(
    `${process.env.DB_HOST}/api/categories`
  );

  const products = await productsResponse.json();
  const categories = await categoriesResponse.json();

  return { products: products, categories: categories };
};
