import Head from 'next/head';
import styles from '@/styles/Home.module.css';

import { useState, useEffect } from 'react';
export default function Home({ categories, products }) {
  // const [products, setProducts] = useState([]);

  // useEffect(() => {
  //   getData();
  // }, []);

  // const getData = async () => {
  //   const results = await fetch('/api/products');
  //   const resultsJson = await results.json();
  //   setProducts(resultsJson);
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        {products.map((product) => (
          <div key={product._id}>
            <h1>{product.title}</h1>
          </div>
        ))}
      </main>
    </>
  );
}

Home.getInitialProps = async (ctx) => {
  const productsResponse = await fetch(`http://localhost:3000/api/products`);
  const categoriesResponse = await fetch(
    `http://localhost:3000/api/categories`
  );

  const products = await productsResponse.json();
  const categories = await categoriesResponse.json();

  return { products: products, categories: categories.categories };
};
